language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
  - npm run flow
# blocklist master branch as it's used for github page
branches:
  except:
  - master
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  target-branch: master
  local_dir: build
  on:
    branch: development
