language: node_js
node_js:
  - 6
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test
  - npm run flow
# blocklist master branch as it's used for github page
branches:
  except:
  - master
